config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resource :calendar, only: [:show], controller: :calendar
  root to: 'calendar#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/calendar/show.html.erb
<div class="row ">
  <div class="col-md-4 text-center calendar_control">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="fa-solid fa-backward"></i>
      <% end %>

      <%= "#{@date.year} 年　#{@date.strftime("%m")}月" %>

      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="fa-solid fa-forward"></i>
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 calendar_control">
    <%= calendar @date do |date| %>
      <%= date.day %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 calendar_control">
	<div class="schedule">
    今後の活動一覧
    <table id="schedule" class="table schedule">
      <thead class="thead-light">
        <tr>
          <th>日程</th>
          <th>活動</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>

<div id='dialog' style='display: none;'>
  <input id="input1" type="text" />
</div>

<% content_for :inline_javascript do %>
  <script>
    $(".calendar").on("click", "td", function() {
      if($(this).is(".not-month")) return; // Block the other month
      var date = $(this).text().trim();
      var yearmonth = '<%= @date.year%>' + '-' + '<%= @date.strftime("%m") %>' + '-' + date;
      $("#dialog").dialog({
        modal:true,
        title:"活動",
        buttons: {
        "確認": function() {
          var row = '<tr><td>' + yearmonth + '</td><td>' + $("#input1").val() + '</tr>';
          $('#schedule > tbody').append(row);
          $(this).dialog("close");
          $("#input1").val("");
          },
        "キャンセル": function() {
          $(this).dialog("close"); 
          }
        }
      });
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :inline_javascript %>
  </body>

</html>